### ISSUE TITLE
Import errors with newer coverage

### ISSUE THREAD

**Issue by meejah** [TheCleric/coverage-lcov#10]
Any `coverage >= 7.0.0` breaks lcov with an import error:

```
Traceback (most recent call last):
  File "/home/meejah/src/txtorcon/venv/bin/coverage-lcov", line 5, in <module>
    from coverage_lcov.cli import main
  File "/home/meejah/src/txtorcon/venv/lib/python3.11/site-packages/coverage_lcov/cli.py", line 3, in <module>
    from .converter import Converter
  File "/home/meejah/src/txtorcon/venv/lib/python3.11/site-packages/coverage_lcov/converter.py", line 5, in <module>
    from coverage.files import FnmatchMatcher, prep_patterns
ImportError: cannot import name 'FnmatchMatcher' from 'coverage.files' (/home/meejah/src/txtorcon/venv/lib/python3.11/site-packages/coverage/files.py)
```

**Comment by TheCleric** [comment]
Should be fixed with version 0.3.0 as implemented in #14
